// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qegejcylymgdaapnrsyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlZ2VqY3lseW1nZGFhcG5yc3lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4OTI1OTMsImV4cCI6MjA1OTQ2ODU5M30.KyCGWuPYDIkNADzIKf_cXlb2vyo8PvmSXX4fX0QLIys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);